version: "3.8"

services:
  podcast-app-db:
    image: mariadb
    container_name: podcast-app-db
    environment:
      MARIADB_USER: app_user
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: "podcast"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

  podcast-app-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: podcast-app-server
    depends_on:
      - podcast-app-db
    environment:
      PORT: "5545"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      DB_HOST: podcast-app-db
      DB_PORT: "3306"
      DB_USER: app_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: podcast
    ports:
      - "5545:5545"

  static-server:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - podcast-app-server
    container_name: myapp-static-server
    ports:
      - "8080:8080"

volumes:
  db_data:
  client_build:
