version: "3.8"

services:
  podcast-app-db:
    image: postgres:15
    container_name: podcast-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: podcast
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  podcast-app-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: podcast-app-server
    depends_on:
      - podcast-app-db
    environment:
      PORT: "5545"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      DB_HOST: podcast-app-db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: podcast
    ports:
      - "5545:5545"

  static-server:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - podcast-app-server
    container_name: myapp-static-server
    ports:
      - "8080:8080"

volumes:
  db_data:
  client_build:
